# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 809d91906ae6abb5d46ecc68b1c6f14d70abd860b50b2ac28b38ef297dd951c04470115260ed46ad595f1f0658d96d9e5f7a46172807d6dde8ef30729240bc42

test:
  secret_key_base: 9dc40b4346dce7895bd17593c4ad99c4f347a1a54a665ad7c71f6b3c6f5523453976e41964b66444c1dc2bdee2b22c0b52c36568f631758814d2fd6b12605494

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
